name: Check index.html

on:
  push:
  pull_request:

jobs:
  file-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Verify index.html exists
        run: |
          if [ -f "index.html" ]; then
            echo "index.html exists."
          else
            echo "index.html not found."
            exit 1
          fi